[req]
default_bits = 2048
prompt = no
default_md = sha256
distinguished_name = dn
req_extensions = v3_req

[dn]
C=US
ST=Local
L=Local
O=Local Development
OU=IT Department
CN=local.test

[v3_req]
basicConstraints = CA:FALSE
keyUsage = nonRepudiation, digitalSignature, keyEncipherment
subjectAltName = @alt_names

[alt_names]
DNS.1 = local.test
DNS.2 = *.local.test
DNS.3 = traefik.local.test
DNS.4 = whoami.local.test
DNS.5 = app.local.test
